ARG VERSION=latest
FROM mbari/lcm-websocket-server:$VERSION-compas-lcmtypes

# Install lcm-websocket-server with the image extra
RUN pip install $(ls /tmp/*.whl | head -n 1)[image]

ENV JPEG_QUALITY=75
ENV JPEG_SCALE=1.0

# Run lcm-websocket-dial-proxy
CMD lcm-websocket-dial-proxy -vv --host "$HOST" --port "$PORT" --channel "$CHANNEL" --quality "$JPEG_QUALITY" --scale "$JPEG_SCALE"
