"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

from .channel_stats import channel_stats

class channel_stats_list(object):
    __slots__ = ["num_channels", "channels"]

    __typenames__ = ["int32_t", "channel_stats"]

    __dimensions__ = [None, ["num_channels"]]

    def __init__(self):
        self.num_channels = 0
        self.channels = []

    def encode(self):
        buf = BytesIO()
        buf.write(channel_stats_list._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.num_channels))
        for i0 in range(self.num_channels):
            assert self.channels[i0]._get_packed_fingerprint() == channel_stats._get_packed_fingerprint()
            self.channels[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != channel_stats_list._get_packed_fingerprint():
            raise ValueError("Decode error")
        return channel_stats_list._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = channel_stats_list()
        self.num_channels = struct.unpack(">i", buf.read(4))[0]
        self.channels = []
        for i0 in range(self.num_channels):
            self.channels.append(channel_stats._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if channel_stats_list in parents: return 0
        newparents = parents + [channel_stats_list]
        tmphash = (0x557ed5e44cc122a9+ channel_stats._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if channel_stats_list._packed_fingerprint is None:
            channel_stats_list._packed_fingerprint = struct.pack(">Q", channel_stats_list._get_hash_recursive([]))
        return channel_stats_list._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", channel_stats_list._get_packed_fingerprint())[0]

